#:kivy 2.0
#:import Factory kivy.factory.Factory

<ActionButton>:
    font_size:15
    color: 1,1,1,1
    background_normal: ''
    background_color: 0.4,0.4,0.4,1

<GateButton@Button>:
    text: "gate"
    font_size: 30
    size_hint: None, None
    center: self.parent.center

<ToolToggleButton@ToggleButton>:
    font_size: 10
    size_hint_y: None
    size: 50,50
    pos_hint: {"center_x":0.5}
    allow_no_selection: False

<ToolButton@Button>:
    font_size: 10
    size_hint_y: None
    size: 50,50
    pos_hint: {"center_x":0.5}

<GateLabel@Label>:
    font_size: 30
    color: 0,0,0,1

<ExitPopup>:
    auto_dismiss: True
    title_color: 0,0,0,1
    title_size: 18
    title: "Are you sure you want to quit?\nAny unsaved progress will be lost"
    size_hint: None, None
    size: 350,150
    BoxLayout:
        Button:
            text: 'Cancel'
            on_release: root.dismiss()
        Button:
            text: 'Quit'
            on_release: root.closeWindow()

<TruthPopup>:
    auto_dismiss: True
    title_color: 0,0,0,1
    title_size: 18
    title: "Truth Table Generator"
    size_hint: 0.6, 0.8
    BoxLayout:
        orientation: "vertical"
        ScrollView:
            size_hint: 1, 0.6
            do_scroll_x: False
            effect_cls: "ScrollEffect"
            Label:
                id: truth_label
                size_hint_y: None
                text_size: self.width, None
                height: self.texture_size[1]
                color: (0,0,0,1)
                text: "YOOOOOOO"
        TextInput:
            id: truth_input
            text: Enter Boolean Expression
            size_hint: 1, 0.2
        GridLayout:
            size_hint: 1, 0.2
            rows: 1
            columns: 2
            Button:
                text: 'Cancel'
                on_release: root.dismiss()
            Button:
                text: 'Generate' 
                on_release: root.generate()


<GridLayout>:
    padding: 2
    spacing: 2
    canvas.before:
        Color:
            rgba: (0.8,0.8,0.8,1)
        Rectangle:
            pos: self.pos
            size: self.size

<MainWindow>:

    GridLayout:
        size: root.width, root.height
        rows:2
        orientation: "tb-lr"
        ActionBar:
            height: 30
            pos_hint: {"top":1}
            ActionView:
                spacing: 2
                padding: 2
                ActionPrevious:
                    with_previous: False
                    font_size: 40
                    markup: True
                    title: " [b]Logic Gate Simultor[/b]"
                    app_icon: "Images/Me.jpg"
                    app_icon_height: 0
                    app_icon_width: 0
                ActionButton:
                    text: "Truth Table"
                    on_release: Factory.TruthPopup().open()
                ActionButton:
                    text: "Save"
                ActionButton:
                    text: "Load"
                ActionButton:
                    text: "Help"
                ActionButton:
                    text: "Quit"
                    on_release: Factory.ExitPopup().open()
                
        
        GridLayout:
            size: self.parent.width, self.parent.height
            orientation: "tb-rl"
            cols: 3
            padding: 0
            GridLayout:
                orientation: "tb-lr"
                cols:1
                size_hint: None, 1
                width: 50
                ToolToggleButton:
                    id: connectToggle
                    group: "tools"
                    text: "Connect"
                    on_press: root.setTool("connect")
                ToolToggleButton:
                    id: disconnectToggle
                    group: "tools"
                    text: "Disconnect"
                    on_press: root.setTool("disconnect")
                ToolToggleButton:
                    id: moveToggle
                    state: "down"
                    group: "tools"
                    text: "Move"
                    on_press: root.setTool("move")
                ToolButton:
                    text: "Delete"
                    on_press: root.deleteGates()
                ToolButton:
                    text: "Clear"
                    on_press: root.clearCanvas()
                Label:
                    id: toolLabel
                    color: 0,0,0,1
                    text: gateCanvas.tool
            GateCanvas:
                id: gateCanvas
                canvas.before:
                    Color:
                        rgba: (0.1,0.6,0.6,1)
                    Rectangle:
                        pos: map(lambda x: x+5, self.pos)
                        size: map(lambda x: x-10, self.size)
                canvas.after:
                    Color:
                        rgba: (1,0,0,1)
                    Line:
                        width: 4
                        rectangle: (self.x+2, self.y+2, self.width-4, self.height-4)
            ScrollView:
                size_hint: None, 1
                width: 200
                GridLayout:
                    size_hint_y: None
                    height: 900
                    cols: 1
                    rows: 2
                    Label:
                        size_hint: 1,0.1
                        markup: True
                        font_size: 40
                        color: 0,0,0,1
                        text: "[b]Gates[/b]"
                    GridLayout:
                        cols: 2
                        spaceing: 1
                        padding: 1
                        size: self.parent.size
                        GateLabel:
                            text: "And"
                        GateButton:
                            id: And
                            on_press: root.addGateToCanvas("and")
                        GateLabel:
                            text: "Or"
                        GateButton:
                            id: Or
                            on_press: root.addGateToCanvas("or")
                        GateLabel:
                            text: "Not"
                        GateButton:
                            id: Not
                            on_press: root.addGateToCanvas("not")
                        GateLabel:
                            text: "Xor"
                        GateButton:
                            id: Xor
                            on_press: root.addGateToCanvas("xor")
                        GateLabel:
                            text: "Input"
                        GateButton:
                            id: Input
                            on_press: root.addGateToCanvas("input")
                        GateLabel:
                            text: "Output"
                        GateButton:
                            id: Output
                            on_press: root.addGateToCanvas("output")
                        GateLabel:
                            text: "Clock"
                        GateButton:
                            id: Clock
                            on_press: root.addGateToCanvas("clock")
                